name: Test GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 22f2001205@ds.study.iitm.ac.in
        run: echo "Hello, world!"
